In [1]:
# ================================
# 📦 IMPORT SECTION
# ================================
import os, sys, json, time
import pandas as pd
from ast import literal_eval
from typing import List, Dict, Any

from langchain_huggingface import HuggingFaceEmbeddings
from ragas.dataset_schema import EvaluationDataset, EvaluationResult
from IPython.display import display

# Tambahkan path lokal ke modul `src/`
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))

from src.tag.src.init_llm import init_llm
from src.tag.src.answer_generator import generate_answer
from src.tag.evaluation.eval_metrics import evaluate_text_generation

d:\code\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# ================================
# 🧪 DEFINE TEST CASES
# ================================
answer_test_cases = [
    {
        "experiment_name": "generate_answer_eval_claude_zero_shot",
        "llm_mode": "claude",
        "shot_mode" : "zero_shot",
        "embedding_model": "sentence-transformers/all-MiniLM-L6-v2"
    },
    {
        "experiment_name": "generate_answer_eval_claude_few_shot",
        "llm_mode": "claude",
        "shot_mode" : "few_shot",
        "embedding_model": "sentence-transformers/all-MiniLM-L6-v2"
    },
    {
        "experiment_name": "generate_answer_eval_ollama",
        "llm_mode": "ollama",
        "embedding_model": "sentence-transformers/all-MiniLM-L6-v2"
    }
]

In [4]:
DATASET_PATH = os.path.join("data", "Dataset Testing Archive 2.xlsx")
df = pd.read_excel(DATASET_PATH)

dataset = []

# Filter for "is_valid" rows first, then sample
valid_df = df[df["is_valid"]]

# Sample 85 rows randomly from the valid_df
# If there are fewer than 85 valid rows, it will take all of them.
sampled_df = valid_df.head(100)

for i, row in sampled_df.iterrows():
    dataset.append({
        "user_input": str(row["user_input"]),
        "reference_contexts": literal_eval(row["reference_contexts_2"]),
        "reference": str(row["reference"]),
        "response": str(row.get("response", ""))  # kosongkan jika belum ada
    })

print(f"Jumlah soal: {len(dataset)}")

Jumlah soal: 100

In [3]:
# ================================
# 📥 LOAD DATASET
# ================================
def load_evaluation_dataset(
    path: str = "data/Dataset Testing Archive 2.xlsx",
    n_samples: int = 100,
    random_seed: int = 42
) -> List[Dict]:
    """
    Load dan sampling dataset evaluasi.
    """
    df = pd.read_excel(path)
    valid_df = df[df["is_valid"]]
    sampled_df = valid_df.sample(n=min(n_samples, len(valid_df)), random_state=random_seed)

    dataset = []
    for _, row in sampled_df.iterrows():
        try:
            dataset.append({
                "user_input": str(row["user_input"]),
                "reference_contexts": literal_eval(row["reference_contexts_2"]),
                "reference": str(row["reference"]),
                "response": str(row.get("response", ""))  # kosongkan jika belum ada
            })
        except Exception as e:
            print(f"❌ Error parsing row: {e}")
            continue

    print(f"✅ Jumlah soal yang dimuat: {len(dataset)}")
    return dataset

In [5]:
def retry_until_success(func, *args, max_delay=60, base_delay=5, **kwargs):
    """
    Melakukan retry berulang dengan backoff jika error Claude overload (kode 529).
    """
    delay = base_delay
    while True:
        try:
            return func(*args, **kwargs)
        except Exception as e:
            error_msg = str(e).lower()
            if "overload" in error_msg or "529" in error_msg:
                print(f"⚠️ Claude overload. Menunggu {delay} detik lalu retry...")
                time.sleep(delay)
                delay = min(delay * 2, max_delay)  # backoff maksimal 60 detik
            else:
                print(f"❌ Error bukan overload: {e}")
                raise  # error lain (misal bug prompt) tetap dilempar

def save_checkpoint_json(data: Any, filename: str):
    os.makedirs("samples", exist_ok=True)
    path = os.path.join("samples", filename)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"✅ Saved: {filename}")
            
def run_single_answer_test_case(test_case: dict, dataset: List[Dict]) -> Dict:
    """
    Evaluasi Answer Generation: generate jawaban LLM lalu evaluasi dengan metrik RAGAS.
    """
    print(f"\n🚀 Evaluasi Answer Generation: {test_case['experiment_name']}")

    llm_mode = test_case["llm_mode"]
    llm_model = init_llm(mode="evaluator")
    shot_mode = test_case["shot_mode"]
    embedding_model = HuggingFaceEmbeddings(model_name=test_case["embedding_model"])
    experiment_name = test_case["experiment_name"]

    samples = []
    for idx, d in enumerate(dataset):
        question = d["user_input"]
        contexts = d["reference_contexts"]
        reference = d["reference"]

        # Siapkan input untuk LLM dalam format tabel
        columns = ["teks"]
        rows = [[ctx] for ctx in contexts]

        # 🔄 Generate jawaban dari LLM
        try:
            answer = retry_until_success(generate_answer, columns, rows, question, mode=shot_mode, llm_mode=llm_mode)
        except Exception as e:
            print(f"❌ Gagal generate jawaban untuk: {question}\n{e}")
            answer = "jawaban tidak tersedia"
        
        sample = {
            "user_input": question,
            "retrieved_contexts": contexts,
            "response": answer,
            "reference": reference
        }

        samples.append(sample)
        
        # ✅ Autosave setiap 3 soal
        if (idx + 1) % 3 == 0:
            save_checkpoint_json(samples, f"{experiment_name}_autosave.json")
    
          # 💾 Save hasil akhir
    save_checkpoint_json(samples, f"{experiment_name}_samples.json")

        
        # 💤 Sleep setiap x soal
        # if (idx + 1) % 5 == 0 and (idx + 1) < len(dataset):
        #     print("⏳ Menunggu 15 detik sebelum lanjut ke batch berikutnya...\n")
        #     time.sleep(15)

   
    # 🔎 Evaluasi batch per 8  
    batch_size = 8
    results = []

    for i in range(0, len(samples), batch_size):
        batch = samples[i:i+batch_size]
        batch_dataset = EvaluationDataset.from_list(batch)

        print(f"🔎 Mengevaluasi batch {i//batch_size + 1} ({len(batch)} soal)")
        result = evaluate_text_generation(
            evaluation_dataset=batch_dataset,
            llm_model=llm_model,
            embedding_model=embedding_model,
            experiment_name=f"answer_eval_batch_{i//batch_size + 1}"
        )
        results.append(result)

        if i + batch_size < len(samples):
            print("🕒 Sleeping 20 detik...\n")
            time.sleep(15)

    # 📊 Tampilkan hasil
    df_result = result.to_pandas()
    print("\n📊 Hasil Evaluasi:")
    display(df_result)

    return {
        "experiment_name": test_case["experiment_name"],
        "evaluation_result": results,
        "samples": samples  # optional: bisa simpan jawaban LLM
    }

In [6]:
from collections import defaultdict

def summarize_scores_from_result_list(results: List[Dict]) -> None:
    """
    Menerima list of result dari run_single_answer_test_case dan
    menampilkan rata-rata skor per metrik dari EvaluationResult.scores.
    """
    combined_scores = defaultdict(list)

    for result_dict in results:
        result = result_dict["evaluation_result"]
        for score_dict in result.scores:  # result.scores = list of dict
            for metric_name, score in score_dict.items():
                combined_scores[metric_name].append(score)

    print("\n📊 RATA-RATA EVALUASI KESELURUHAN:")
    print("-" * 60)
    for metric, scores in combined_scores.items():
        avg_score = sum(scores) / len(scores)
        print(f"{metric:<35}: {avg_score:.4f}")

## **CLAUDE**

**ZERO SHOT**

In [7]:
result_api = run_single_answer_test_case(answer_test_cases[0], dataset)

🚀 Evaluasi Answer Generation: generate_answer_eval_claude_zero_shot

d:\code\.venv\Lib\site-packages\transformers\tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_autosave.json
✅ Saved: generate_answer_eval_claude_zero_shot_samples.json
🔎 Mengevaluasi batch 1 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:11<00:00,  3.40it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 2 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:08<00:00,  4.92it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 3 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:08<00:00,  4.55it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 4 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:13<00:00,  2.98it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 5 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:09<00:00,  4.30it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 6 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:09<00:00,  4.07it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 7 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:29<00:00,  1.34it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 8 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:08<00:00,  4.79it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 9 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:09<00:00,  4.34it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 10 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:12<00:00,  3.30it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 11 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:11<00:00,  3.57it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 12 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:05<00:00,  6.79it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 13 (4 soal)

Evaluating: 100%|██████████| 20/20 [00:13<00:00,  1.53it/s]

📊 Hasil Evaluasi:

,user_input,retrieved_contexts,response,reference,rougeL_precision(mode=precision),rougeL_recall(mode=recall),rougeL_fmeasure(mode=fmeasure),answer_relevancy,faithfulness
0,Apa hubungan atau relasi antara Pasal 40 UU No...,[{'relation_type': 'mengubah'}],Pasal 40 UU Nomor 19 Tahun 2016 mengubah Pasal...,Hubungan antara Pasal 40 UU Nomor 19 Tahun 201...,0.571429,0.651163,0.608696,0.277954,1.000000
1,Sebutkan semua judul peraturan yang mengatur t...,[{'title': 'Peraturan Menteri Komunikasi dan I...,Peraturan Menteri Komunikasi dan Informatika N...,Peraturan yang mengatur tentang persyaratan te...,0.514286,0.620690,0.562500,0.199649,0.666667
2,Pasal nomor berapa saja dalam UU Nomor 11 Tahu...,"[{'number': '1'}, {'number': '5'}, {'number': ...",Pasal-pasal dalam UU Nomor 11 Tahun 2008 yang ...,Berikut adalah daftar pasal dalam UU Nomor 11 ...,0.918919,0.566667,0.701031,0.428733,0.000000
3,Judul peraturan apa saja yang mengatur tentang...,[{'title': 'Peraturan Menteri Komunikasi dan I...,Peraturan yang mengatur tentang penggunaan jar...,"Berdasarkan hasil kueri, peraturan yang mengat...",0.957746,0.759777,0.847352,0.464866,1.000000

In [9]:
all_results_zero = [{"evaluation_result": r} for r in result_api["evaluation_result"]]
                   
summarize_scores_from_result_list(all_results_zero)

📊 RATA-RATA EVALUASI KESELURUHAN:
------------------------------------------------------------
rougeL_precision(mode=precision)   : 0.5673
rougeL_recall(mode=recall)         : 0.5754
rougeL_fmeasure(mode=fmeasure)     : 0.5356
answer_relevancy                   : 0.3775
faithfulness                       : 0.8811

**FEW SHOT**

In [10]:
result_api = run_single_answer_test_case(answer_test_cases[1], dataset)

🚀 Evaluasi Answer Generation: generate_answer_eval_claude_few_shot

d:\code\.venv\Lib\site-packages\transformers\tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_autosave.json
✅ Saved: generate_answer_eval_claude_few_shot_samples.json
🔎 Mengevaluasi batch 1 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:11<00:00,  3.46it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 2 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:08<00:00,  4.66it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 3 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:08<00:00,  4.88it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 4 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:12<00:00,  3.11it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 5 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:12<00:00,  3.33it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 6 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:11<00:00,  3.48it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 7 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:31<00:00,  1.28it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 8 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:08<00:00,  4.77it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 9 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:11<00:00,  3.56it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 10 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:10<00:00,  3.73it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 11 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:12<00:00,  3.16it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 12 (8 soal)

Evaluating: 100%|██████████| 40/40 [00:08<00:00,  4.60it/s]

🕒 Sleeping 20 detik...

🔎 Mengevaluasi batch 13 (4 soal)

Evaluating: 100%|██████████| 20/20 [00:11<00:00,  1.78it/s]

📊 Hasil Evaluasi:

,user_input,retrieved_contexts,response,reference,rougeL_precision(mode=precision),rougeL_recall(mode=recall),rougeL_fmeasure(mode=fmeasure),answer_relevancy,faithfulness
0,Apa hubungan atau relasi antara Pasal 40 UU No...,[{'relation_type': 'mengubah'}],Pasal 40 UU Nomor 19 Tahun 2016 mengubah Pasal...,Hubungan antara Pasal 40 UU Nomor 19 Tahun 201...,0.473684,0.627907,0.540000,0.277921,1.0
1,Sebutkan semua judul peraturan yang mengatur t...,[{'title': 'Peraturan Menteri Komunikasi dan I...,Peraturan Menteri Komunikasi dan Informatika N...,Peraturan yang mengatur tentang persyaratan te...,0.514286,0.620690,0.562500,0.197162,0.5
2,Pasal nomor berapa saja dalam UU Nomor 11 Tahu...,"[{'number': '1'}, {'number': '5'}, {'number': ...",Pasal-pasal dalam UU Nomor 11 Tahun 2008 yang ...,Berikut adalah daftar pasal dalam UU Nomor 11 ...,0.918919,0.566667,0.701031,0.428733,1.0
3,Judul peraturan apa saja yang mengatur tentang...,[{'title': 'Peraturan Menteri Komunikasi dan I...,Peraturan yang mengatur tentang penggunaan jar...,"Berdasarkan hasil kueri, peraturan yang mengat...",0.957746,0.759777,0.847352,0.464866,1.0

In [11]:
all_results_few = [{"evaluation_result": r} for r in result_api["evaluation_result"]]
                   
summarize_scores_from_result_list(all_results_few)

📊 RATA-RATA EVALUASI KESELURUHAN:
------------------------------------------------------------
rougeL_precision(mode=precision)   : 0.5691
rougeL_recall(mode=recall)         : 0.5802
rougeL_fmeasure(mode=fmeasure)     : 0.5379
answer_relevancy                   : 0.3817
faithfulness                       : 0.8803

# OLd CoDes

In [8]:
samples = []
for item in tqdm(dataset, desc=f"Running {experiment_name}"):
    q = item["user_input"]
    ref = item["reference_contexts"]
    ground_truth = item["reference"]
    
    # Generate answer using the LLM
    answer = generate_answer(columns, rows, question, llm_mode="api")
    
    samples.append({
            "user_input": q,
            "response": answer,
            "retrieved_contexts": ref,
            "reference": ground_truth
        })

eval_dataset = EvaluationDataset(samples)

# === Evaluasi per 3 soal ===
batch_size = 3
for i in range(0, len(samples), batch_size):
    batch_samples = samples[i:i+batch_size]
    dataset = EvaluationDataset.from_list(batch_samples)

    print(f"\n🧪 Mengevaluasi batch {i//batch_size + 1} ({len(batch_samples)} soal)...")
    result = evaluate_text_generation(
        evaluation_dataset=dataset,
        llm_model=llm_model,
        embedding_model=embedding_model,
        experiment_name=f"eval_batch_answer_generation_{i//batch_size + 1}"
    )
    print(result)

    if i + batch_size < len(samples):
        print("⏳ Menunggu 30 detik sebelum lanjut ke batch berikutnya...\n")
        time.sleep(30)

NameError: name 'experiment_name' is not defined

In [ ]:
# === Load dan filter dataset ===
DATASET_PATH = os.path.join("data", "Dataset Testing 2.xlsx")
df = pd.read_excel(DATASET_PATH)
valid_df = df[df["is_valid"]]
sampled_df = valid_df.sample(n=min(20, len(valid_df)), random_state=42)

# === Hasil akhir: list of dict yang siap evaluasi ===
samples = []

for i, row in sampled_df.iterrows():
    question = str(row["user_input"])
    ground_truth = str(row["reference"])

    try:
        contexts = literal_eval(row["reference_contexts_2"])
        if not isinstance(contexts, list): continue
    except:
        continue

    # Siapkan input tabular untuk generator
    columns = ["teks"]
    rows = [[ctx] for ctx in contexts]

    # Generate jawaban dari sistemmu
    answer = generate_answer(columns, rows, question, mode="few-shot", llm_mode="api")

    samples.append({
        "user_input": question,
        "retrieved_contexts": contexts,
        "response": answer,
        "reference": ground_truth
    })

# Simpan untuk dipakai ulang (opsional)
import json
with open("generated_samples.json", "w", encoding="utf-8") as f:
    json.dump(samples, f, indent=2, ensure_ascii=False)

print(f"Total samples siap evaluasi: {len(samples)}")

Total samples siap evaluasi: 20

In [ ]:
# === Load hasil generate_answer dari file JSON ===
with open("generated_samples.json", "r", encoding="utf-8") as f:
    raw_samples = json.load(f)

# === Bersihkan dan ubah field agar cocok dengan EvaluationDataset ===
samples = []
for s in raw_samples:
    try:
        question = str(s["user_input"])
        answer = str(s["response"])
        ground_truth = str(s["reference"])
        contexts = s["retrieved_contexts"]
        
        if not isinstance(contexts, list) or not all(isinstance(c, str) for c in contexts):
            continue

        samples.append({
            "user_input": question,
            "response": answer,
            "retrieved_contexts": contexts,
            "reference": ground_truth
        })
    except Exception as e:
        print(f"❌ Error pada sample: {e}")
        continue

print(f"✅ Total sample valid untuk evaluasi: {len(samples)}")

# === Inisialisasi LLM dan Embedding ===
llm_model = init_llm(mode="gemini")  # sesuai mode generate_answer
embedding_model = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# === Evaluasi per 3 soal ===
batch_size = 3
for i in range(0, len(samples), batch_size):
    batch_samples = samples[i:i+batch_size]
    dataset = EvaluationDataset.from_list(batch_samples)

    print(f"\n🧪 Mengevaluasi batch {i//batch_size + 1} ({len(batch_samples)} soal)...")
    result = evaluate_text_generation(
        evaluation_dataset=dataset,
        llm_model=llm_model,
        embedding_model=embedding_model,
        experiment_name=f"eval_batch_answer_generation_{i//batch_size + 1}"
    )
    print(result)

    if i + batch_size < len(samples):
        print("⏳ Menunggu 30 detik sebelum lanjut ke batch berikutnya...\n")
        time.sleep(30)

✅ Total sample valid untuk evaluasi: 20

d:\code\.venv\Lib\site-packages\transformers\tokenization_utils_base.py:1617: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be deprecated in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

🧪 Mengevaluasi batch 1 (3 soal)...

Evaluating: 100%|██████████| 24/24 [00:14<00:00,  1.71it/s]

{'rouge1_precision(mode=precision)': 0.4993, 'rouge1_recall(mode=recall)': 0.6964, 'rouge1_fmeasure(mode=fmeasure)': 0.4970, 'rougeL_precision(mode=precision)': 0.4454, 'rougeL_recall(mode=recall)': 0.6596, 'rougeL_fmeasure(mode=fmeasure)': 0.4560, 'answer_relevancy': 0.3646, 'faithfulness': 1.0000}
⏳ Menunggu 30 detik sebelum lanjut ke batch berikutnya...


🧪 Mengevaluasi batch 2 (3 soal)...

Evaluating: 100%|██████████| 24/24 [00:12<00:00,  1.93it/s]

{'rouge1_precision(mode=precision)': 0.4461, 'rouge1_recall(mode=recall)': 0.7084, 'rouge1_fmeasure(mode=fmeasure)': 0.5056, 'rougeL_precision(mode=precision)': 0.3800, 'rougeL_recall(mode=recall)': 0.5942, 'rougeL_fmeasure(mode=fmeasure)': 0.4301, 'answer_relevancy': 0.6904, 'faithfulness': 1.0000}
⏳ Menunggu 30 detik sebelum lanjut ke batch berikutnya...


🧪 Mengevaluasi batch 3 (3 soal)...

Evaluating: 100%|██████████| 24/24 [00:11<00:00,  2.07it/s]

{'rouge1_precision(mode=precision)': 0.4744, 'rouge1_recall(mode=recall)': 0.3203, 'rouge1_fmeasure(mode=fmeasure)': 0.3692, 'rougeL_precision(mode=precision)': 0.4225, 'rougeL_recall(mode=recall)': 0.2764, 'rougeL_fmeasure(mode=fmeasure)': 0.3238, 'answer_relevancy': 0.1882, 'faithfulness': 1.0000}
⏳ Menunggu 30 detik sebelum lanjut ke batch berikutnya...


🧪 Mengevaluasi batch 4 (3 soal)...

Evaluating:  88%|████████▊ | 21/24 [00:02<00:00,  7.90it/s]WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 23
}
].
Evaluating:  92%|█████████▏| 22/24 [00:05<00:00,  2.55it/s]WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 20
}
].
WARNING:langchain_google_genai.chat_models:Retrying langchain_google_genai.chat_models._achat_with_retry.<locals>._achat_with_retry in 2.0 seconds as it raised ResourceExhausted: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. [violations {
  quota_metric: "generativelanguage.googleapis.com/generate_content_free_tier_requests"
  quota_id: "GenerateRequestsPerMinutePerProjectPerModel-FreeTier"
  quota_dimensions {
    key: "model"
    value: "gemini-2.0-flash"
  }
  quota_dimensions {
    key: "location"
    value: "global"
  }
  quota_value: 15
}
, links {
  description: "Learn more about Gemini API quotas"
  url: "https://ai.google.dev/gemini-api/docs/rate-limits"
}
, retry_delay {
  seconds: 16
}
].
Evaluating: 100%|██████████| 24/24 [00:18<00:00,  1.33it/s]

{'rouge1_precision(mode=precision)': 0.3574, 'rouge1_recall(mode=recall)': 0.8952, 'rouge1_fmeasure(mode=fmeasure)': 0.4911, 'rougeL_precision(mode=precision)': 0.3381, 'rougeL_recall(mode=recall)': 0.8514, 'rougeL_fmeasure(mode=fmeasure)': 0.4651, 'answer_relevancy': 0.3900, 'faithfulness': 0.9630}
⏳ Menunggu 30 detik sebelum lanjut ke batch berikutnya...


🧪 Mengevaluasi batch 5 (3 soal)...

Evaluating: 100%|██████████| 24/24 [00:22<00:00,  1.06it/s]

{'rouge1_precision(mode=precision)': 0.5501, 'rouge1_recall(mode=recall)': 0.9861, 'rouge1_fmeasure(mode=fmeasure)': 0.6740, 'rougeL_precision(mode=precision)': 0.5464, 'rougeL_recall(mode=recall)': 0.9807, 'rougeL_fmeasure(mode=fmeasure)': 0.6697, 'answer_relevancy': 0.3562, 'faithfulness': 1.0000}
⏳ Menunggu 30 detik sebelum lanjut ke batch berikutnya...


🧪 Mengevaluasi batch 6 (3 soal)...

Evaluating: 100%|██████████| 24/24 [00:19<00:00,  1.25it/s]

{'rouge1_precision(mode=precision)': 0.3928, 'rouge1_recall(mode=recall)': 0.7281, 'rouge1_fmeasure(mode=fmeasure)': 0.4746, 'rougeL_precision(mode=precision)': 0.3895, 'rougeL_recall(mode=recall)': 0.7126, 'rougeL_fmeasure(mode=fmeasure)': 0.4693, 'answer_relevancy': 0.2301, 'faithfulness': 1.0000}
⏳ Menunggu 30 detik sebelum lanjut ke batch berikutnya...


🧪 Mengevaluasi batch 7 (2 soal)...

Evaluating: 100%|██████████| 16/16 [00:20<00:00,  1.29s/it]

{'rouge1_precision(mode=precision)': 0.4095, 'rouge1_recall(mode=recall)': 0.8321, 'rouge1_fmeasure(mode=fmeasure)': 0.5402, 'rougeL_precision(mode=precision)': 0.3688, 'rougeL_recall(mode=recall)': 0.7577, 'rougeL_fmeasure(mode=fmeasure)': 0.4883, 'answer_relevancy': 0.2630, 'faithfulness': 1.0000}

In [15]:
all_results = []
all_results.append(result)
# === Rata-rata skor keseluruhan ===
from collections import defaultdict

# Kumpulkan semua skor berdasarkan metr
# ik
combined_scores = defaultdict(list)

for result in all_results:
    for batch_dict in result.scores:  # result.scores adalah list of dict
        for metric_name, score in batch_dict.items():
            combined_scores[metric_name].append(score)

# Tampilkan rata-rata per metrik
print("\n📊 RATA-RATA EVALUASI KESELURUHAN:")
for metric, scores in combined_scores.items():
    avg_score = sum(scores) / len(scores)
    print(f"{metric}: {avg_score:.4f}")

📊 RATA-RATA EVALUASI KESELURUHAN:
rouge1_precision(mode=precision): 0.4095
rouge1_recall(mode=recall): 0.8321
rouge1_fmeasure(mode=fmeasure): 0.5402
rougeL_precision(mode=precision): 0.3688
rougeL_recall(mode=recall): 0.7577
rougeL_fmeasure(mode=fmeasure): 0.4883
answer_relevancy: 0.2630
faithfulness: 1.0000